const express = require('express');
const { createBlog, updateBlog, getBlog, getAllBlogs, deleteBlog } = require('../controller/blogController');
const { authMiddleware,isAdmin } = require('../middlewares/authMiddleware');
const route = express.Router();
route.post('/create-blog',authMiddleware,isAdmin,createBlog);
route.put('/update-blog/:id',authMiddleware,isAdmin,updateBlog);
route.get('/get-blog/:id',getBlog);
route.get('/getAllBlogs',getAllBlogs);
route.delete('/delete-blog/:id',authMiddleware,isAdmin,deleteBlog);
module.exports = route;